import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sider from "@/components/Sider";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "VideoTube",
    template: "%s | VideoTube",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ResizablePanelGroup
            direction="vertical"
            className="min-h-[100vh] w-full p-0 rounded-lg border"
          >
            <ResizablePanel className="min-h-20 max-h-20 ">
              <div className="flex h-full items-center">
                <Header />
              </div>
            </ResizablePanel>
            <ResizableHandle />
            <ResizablePanel>
              <ResizablePanelGroup direction="horizontal">
                <ResizablePanel className="min-w-fit max-w-fit">
                  <div className="flex w-fit">
                    <Sider />
                  </div>
                </ResizablePanel>
                <ResizableHandle />
                <ResizablePanel>{children}</ResizablePanel>
              </ResizablePanelGroup>
            </ResizablePanel>
          </ResizablePanelGroup>
          {/* <Footer /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
